---
name: Lint Code Base
env:
  VALIDATE_JSON: true
on:
  # push:
  #  branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base for JSON correctness
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check that GUIDs are unique
        id: checklistlint
        uses: ./.github/actions/get_the_aks_checklist
        with:
          file_extension: 'en.json'
          key_name: 'guid'
          criteria_key: '.metadata.state'  # Remove these last two lines to check all checklists (and not only those in preview)
          criteria_value: 'GA'             # Remove these last two lines to check all checklists (and not only those in preview)
